max_connections = 30
listen_addresses = '*'
shared_buffers = 64MB
effective_cache_size = 256MB
maintenance_work_mem = 16MB
checkpoint_completion_target = 0.9
wal_buffers = 7864kB
default_statistics_target = 100
random_page_cost = 1.1
effective_io_concurrency = 200
work_mem = 655kB
min_wal_size = 256MB
max_wal_size = 1GB
TimeZone = 'UTC'
tcp_keepalives_idle = 120
tcp_keepalives_interval = 5
tcp_keepalives_count = 3
