monolog:
  channels:
    - event
    - deprecation
    - request
    - doctrine
    - jira-api-service

when@dev:
  monolog:
    handlers:
      main:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%/app.log"
        excluded_http_codes: [ 404, 405 ]
        channels: [ "!event", "!deprecation", "!request", "!doctrine", "!jira-api-service", "!console" ]

      event:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%/event.log"
        channels: [ "event" ]

      deprecation:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%/deprecation.log"
        channels: [ "deprecation" ]

      request:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%/request.log"
        channels: [ "request" ]

      doctrine:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%/doctrine.log"
        channels: [ "doctrine" ]

      jira-api-service:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%/jira-api-service.log"
        channels: [ "jira-api-service" ]

      console:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%/console.log"
        channels: [ "console" ]
      # uncomment to get logging in your browser
      # you may have to allow bigger header sizes in your Web server configuration
      #firephp:
      #    type: firephp
      #    level: info
      #chromephp:
      #    type: chromephp
      #    level: info

      syslog_handler:
        type: syslog
        # log error-level messages and higher
        level: error

#      console:
#        type: console
#        process_psr_3_messages: false
#        channels: [ "!event", "!doctrine", "!console" ]

when@test:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [ 404, 405 ]
        channels: [ "!event" ]
      nested:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: debug

when@prod:
  monolog:
    handlers:

      main:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%/app.log"
        excluded_http_codes: [ 404, 405 ]
        channels: [ "!event", "!deprecation", "!request", "!doctrine", "!jira-api-service", "!console" ]

      event:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%/event.log"
        channels: [ "event" ]

      deprecation:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%/deprecation.log"
        channels: [ "deprecation" ]

      request:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%/request.log"
        channels: [ "request" ]

      doctrine:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%/doctrine.log"
        channels: [ "doctrine" ]

      jira-api-service:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%/jira-api-service.log"
        channels: [ "jira-api-service" ]

      console:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%/console.log"
        channels: [ "console" ]
