FROM nginx:1.27-alpine
WORKDIR /var/www
COPY .docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY .docker/nginx/node-upstream/ /etc/nginx/conf.d/
COPY .docker/nginx/node-sites/ /etc/nginx/sites-available/
EXPOSE 80 443
