import { BehaviorSubject } from 'rxjs';

import { LoaderStateService } from './loader-state.service';

describe('Core Services loader-state.service', () => {
  beforeEach(() => {
    vi.useFakeTimers();
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  it('uses autogenerated name and reports true when any loader is true', () => {
    const service = new LoaderStateService();
    const a$ = new BehaviorSubject(false);
    const b$ = new BehaviorSubject(false);
    let current = false;

    service.isLoading$.subscribe((v) => {
      current = v;
    });

    service.addLoader(a$.asObservable());
    service.addLoader(b$.asObservable(), 'b');

    vi.advanceTimersByTime(60);
    expect(current).toBe(false);

    b$.next(true);
    vi.advanceTimersByTime(60);
    expect(current).toBe(true);

    b$.next(false);
    vi.advanceTimersByTime(60);
    expect(current).toBe(false);
  });
});
