import { signal } from '@angular/core';
import { TestBed } from '@angular/core/testing';

import { LoaderStateService } from './loader-state.service';

describe('Core Services loader-state.service', () => {
  beforeEach(() => {
    vi.useFakeTimers();
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  it('uses autogenerated name and reports true when any loader is true', async () => {
    TestBed.configureTestingModule({
      providers: [LoaderStateService],
    });
    const service = TestBed.inject(LoaderStateService);
    const a = signal(false);
    const b = signal(false);

    service.addLoader(a.asReadonly());
    service.addLoader(b.asReadonly(), 'b');

    vi.advanceTimersByTime(60);
    await Promise.resolve();
    expect(service.isLoading()).toBe(false);

    b.set(true);
    vi.advanceTimersByTime(60);
    await Promise.resolve();
    expect(service.isLoading()).toBe(true);

    b.set(false);
    vi.advanceTimersByTime(60);
    await Promise.resolve();
    expect(service.isLoading()).toBe(false);
  });
});
