# docker-compose
version: '3.7'

services:
  jira-logger-reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.6
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - --api.dashboard=true
      - --api.insecure=true

      - --providers.docker=true

      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      web:

  jira-logger-nginx:
    container_name: jira-logger-nginx
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - jira-logger-node
    ports:
      - "8888:80"
    volumes:
      - type: bind
        source: ./dist
        target: /usr/share/nginx/html
      - ./.docker/nginx-conf/nginx.conf:/etc/nginx/conf.d/node.template
    command: 'bash -c "cat /etc/nginx/conf.d/node.template > /etc/nginx/conf.d/default.conf && nginx -g ''daemon off;''"'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jira-logger-nginx.rule=Host(`jira-logger.localhost`)"
    networks:
      - web

  jira-logger-node:
    container_name: jira-logger-node
    hostname: jira-logger-node
    image: node:erbium-bullseye
    working_dir: /home/node/app
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules

volumes:
  node_modules:

networks:
  web:
    ipam:
      driver: default
