services:
  nginx:
    volumes:
      - ./../.logs/jira-logger:/var/log/nginx:rw
  php-fpm:
    volumes:
      - ./../.logs/jira-logger:/var/www/var/log:rw
      - ./../.logs/jira-logger:/var/log/php-fpm:rw
