services:
  php-fpm:
    container_name: "jira-logger-php-fpm"
    build:
      context: ./../
      dockerfile: ./.docker/php-fpm/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_ENV: ${APP_ENV:-prod}
      APP_SECRET: ${APP_SECRET:?APP_SECRET is required}
      DATABASE_URL: ${DATABASE_URL:?DATABASE_URL is required}
      APP_INTERNAL_TIMEZONE: ${APP_INTERNAL_TIMEZONE:-UTC}
      APP_DEFAULT_USER_TIMEZONE: ${APP_DEFAULT_USER_TIMEZONE:-Europe/Riga}
      CORS_ALLOW_ORIGIN: ${CORS_ALLOW_ORIGIN:?CORS_ALLOW_ORIGIN is required}
    volumes:
      - assetsData:/var/www/public/ng:ro
    stop_grace_period: 135s
    healthcheck:
      test: ["CMD-SHELL", "php-fpm -t"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    labels:
      - "traefik.enable=false"
  nginx:
    image: ${COMPOSE_PROJECT_NAME:-jira-logger}-nginx-php
    depends_on:
      php-fpm:
        condition: service_healthy
