version: '3.8'

services:
  traefik:
    container_name: "jira-logger-traefik"
    image: traefik:latest
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./traefik.yaml:/etc/traefik/traefik.yaml"
      - "./certs/:/certs/"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - internalNetwork
      - jiraLoggerNetwork

networks:
  internalNetwork:
    external: false

  jiraLoggerNetwork:
    external: true
