services:
  traefik:
    container_name: "jira-logger-traefik"
    image: traefik:v3.7.1
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./traefik.yaml:/etc/traefik/traefik.yaml:ro"
      - "./certs/:/certs/:ro"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 60s
      timeout: 5s
      retries: 10
      start_period: 10s
