# docker-compose
version: '3.7'

services:
  app:
    build: .
    command: sh -c "npm watch && npm server"
    ports:
      - "8080:8080"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
volumes:
  node_modules:
