version: '3.8'

services:
  db:
    container_name: "jira-logger-db"
    image: postgres:${POSTGRES_VERSION}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      TZ: 'Europe/Riga'
      PGTZ: 'Europe/Riga'
    volumes:
      - dbData:/var/lib/postgresql/data:rw
      - ./postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "15432:5432"
    labels:
      - "traefik.enable=false"

  php-fpm:
    container_name: "jira-logger-php-fpm"
    build:
      context: ./../
      dockerfile: ./.docker/php-fpm/Dockerfile
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    labels:
      - "traefik.enable=false"
    volumes:
      - ./../backend/:/var/www
      - ./../frontend/dist/jira-logger/:/var/www/public/ng

  nginx:
    container_name: "jira-logger-nginx"
    build:
      context: ./../
      dockerfile: ./.docker/nginx/Dockerfile
    volumes:
      - ./../backend/:/var/www
      - ./../frontend/dist/jira-logger/:/var/www/public/ng
      - ./certs/:/etc/ssl/certs/
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php-fpm
      - db
    labels:
      traefik.enable: true
      traefik.http.routers.jira-logger-nginx.rule: Host(`jira-logger.io`)
      traefik.http.routers.jira-logger-nginx.entrypoints: websecure
      traefik.http.routers.jira-logger-nginx.tls: true
      traefik.http.services.jira-logger-nginx.loadbalancer.server.port: 80
    ports:
      - "80"
      - "4433:443"

  node:
    container_name: "jira-logger-node"
    build:
      context: ./../
      dockerfile: ./.docker/node/Dockerfile
    working_dir: /home/node/app
    volumes:
      - ./../frontend/:/home/node/app
    labels:
      - "traefik.enable=false"

volumes:
  dbData:
