[global]
error_log = /var/log/php-fpm/log-php-fpm-error.log

[www]
access.log = /var/log/php-fpm/log-php-fpm-access.log
slowlog = /var/log/php-fpm/log-php-fpm-slow.log
request_slowlog_timeout = 5s
catch_workers_output = yes
decorate_workers_output = no
