server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name jira-logger.io;
    server_tokens off;
    include /etc/nginx/sites-available/locations.inc;
}
server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    http2 on;
    server_name jira-logger.io;
    server_tokens off;
    ssl_certificate /etc/ssl/certs/jira-logger.io.crt;
    ssl_certificate_key /etc/ssl/certs/jira-logger.io.key;
    ssl_protocols TLSv1.3 TLSv1.2;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    include /etc/nginx/sites-available/locations.inc;
}
